### ISSUE TITLE
请教下这个该怎么用

### ISSUE THREAD

**Issue by lqllife** [MenuS77/SkyDraw#2]
请教下，这个是PC端的光遇吗，需要搭建好C的环境再运行代码吗？

**Comment by MenuS77** [comment]
> 请教下，这个是PC端的光遇吗，需要搭建好C的环境再运行代码吗？

ios的

**Comment by lqllife** [comment]
> > 请教下，这个是PC端的光遇吗，需要搭建好C的环境再运行代码吗？
> 
> ios的

ios上要怎么本地运行呢？

**Comment by Laoduan17820** [comment]
同问，plz
